Scalar = 'Union[Rational, Complex]'
Context = 'Dict[str, Union[Rational, Complex, Expr]]'
Value = 'Union[Rational, Complex, Matrix]'
Factor = 'Union[Literal, Expr]'
RationalOrInt = 'Union[int, Rational]'
ScalarOrInt = 'Union[int, Rational, Complex]'
